# -*- coding: utf-8 -*-
print('Hello World')
x=1
print(x)
print(type(x))
age=input('Enter your age:')
print(type(age))
print(age)

age1=input('Enter your age:')
print(type(age1))
print(age1)

age2=input('Enter your age:')
print(type(age2))
print(age2)

age=age1+age2
print(age)

age=int(input('Enter your age:'))
print(type(age))
print(age)

age1=int(input('Enter your age:'))
print(type(age1))
print(age1)

age2=int(input('Enter your age:'))
print(type(age2))
print(age2)

age=age1+age2
print(age)

exchange_rate=1.83
print(exchange_rate)
print(type(exchange_rate))

int_value=100
string_value='1.5'
print(type(string_value))
float_value=float(int_value)
print('int value as a float:',float_value)
print(type(float_value))
float_value1=float(string_value)
print('string value as a float:',float_value1)
print(type(float_value1))
#############
#complex Numbers
c1=1 
c2=2j
print('c1:',c1, ',c2:',c2)
print(type(c1))
print(type(c2))
print(c1.real)
print(c2.imag)
print(c1+c2)
##############
#Boolean Types

all_ok=True
print(all_ok)
all_ok=False
print(type(all_ok))
status=bool(input('Ok it is confiremed:?'))
print(status)
print(type(status))

##################
#Arithmetic operator

home=10
away=15
print(home+away)
print(type(home+away))
print(10*4)
print(type(10*4))
goals_for=10
goals_against=7
print(goals_for-goals_against)
print(type(goals_for-goals_against))

##############
#divide
print(100/20)
print(type(100/20))

############
##To ignore fractional part generated by int/int 
## we use (//) operator to convert result into int

print(100//20)
print(type(100//20))

####
#remainder
print('modulus divison 100 % 13:',100%13)

####power operation
a=5
b=3
print(a**b)

######################
#Arithmetic Operators
x = 0
x += 1 # x=x+1
print(x)

#############
#NONE value
winner=None
print(winner is None)
print(winner is not None)
print('winner:' ,winner)
print(type(winner))

################
#Flow Control

 #prime number in given range
#leap year
#string is palindrome   
##########################################
#prime year
start=int(input('Enter start range:'))
end=int(input('Enter end range:'))
prime=[]
for i in range(start,end+1):
    flag=0
    if i<2:
        continue
    if i==2:
        prime.append(2)
        continue
    for x in range(2,i):
        if i%x==0:
            flag=1
            break
    if flag==0:
        prime.append(i)
print(prime)
##########################################
#leap year
def leap(n):
    if n>0 and n%4==0 or n%100==0 and n%400==0:
        return True
    else:
        return False
n=int(input("Enter a year:"))
leap(n)

##palindrome string
s1=input('Enter string:')
s2=s1[::-1]
if s2==s1:
    print('String is palindome')
else:
    print('String not palindome')

##Mario pyramid very most important que
for i in range(4):
    for j in range(i+1):
        print("*"," ",end='')
    print()
    
for i in range(4):
    for j in range(4-i):
        print("*"," ",end='')
    print()


#prime number
def prime(n):
    for i in range(2,n):
        if n%i==0:
            print("False")
            break
        else:
            print("True")
n=int(input("Enter number :"))
prime(n)
def prinmef(n):
    n=2
    count=0
    for i in range(2,n):
        if n%i==0:
            print("False")
            break
        else:
            print("True")    
prinmef(n)
x,y,z=3,4,5
print(x)
print(y)
print(z)
x,y,z=3
print(x)
print(y)
print(z)

#global variable
x='Sanjivani'
def fun():
    print("Our college is "+x)
fun()  

#local variable
def fun():
    x='Sanjivani'
    print("Our college is "+x)
fun()  

x='kopargaon'
def fun():
    x='Sanjivani'
    print("Our college is "+x)
fun() 
print("Our college is "+x)

#dict
dict={"name":"Urmila","age":34}
print(type(dict))
print(dict.keys())
print(dict.values())
str1='urmila'
str2=12
print(str1+str2)#we can not concatenate string with integer if give error

#multiple string
str=""" this is python. it is very powerful"""
print(str)

#string slicing 
x='sanjivani'
print(x[2:5])
print(x[:-10:-1])
print(x[-2:-8:-1])
print(x[:-8:-1])

str="""this is python. it is very powerful"""
print(str[2:8])

str="""this is python. it is very powerful"""
print(str[2:])

str="""this is python. it is very powerful"""
print(str[:8])

str="""this is python. it is very powerful"""
print(str[:-10:-1])

str="""this is python. it is very powerful"""
print(str[-2:-10:-1])

str="""this is python.it is very powerful"""
print(str[-10:-2])

#modify strings
str="""  this is python.it is very powerful"""
print(str.upper())
print(str.strip())
print(str.replace('python','C++'))
print(str.split('.'))
print(str.find('very'))

x='sanjivani college'
print(x.split(' '))

string='hello world'
string1=string[::-1]
string2=string[::-2]
print(string1)
print(string2)

#number manipulation and f string in python
x1='sanjivani college'
x=36
print(f'my age is:{x}')

x1='sanjivani college'
x=36
y=str('36')
print(x1+" "+y)

quantity=12
item_no=10
price=100
print(f"I want {quantity},pieces and item number is {item_no},its price is {price}")

quantity=12
item_no=10
price=100
str="I want {},pieces and item number is {},its price is {}"
print(str.format(quantity,item_no,price))
print("I want {},pieces and item number is {},its price is {}".format(quantity,item_no,price))

#Escape charcter
print("Hello i am rucha from \"computer department\"")

a=10
b=20
print(a!=b)

lst1=[1,2,3,4,5,6,7,8,9,10]
lst2=[i**2 for i in lst1 if i%2==0]
print(lst2)

lst=['west indies','west bangal']
lst1=[x[5:] for x in lst]
print(lst1)

flag=0
num=int(input("Enter number")) 
if num==1:
    print("not prime")
elif num>1:
    for i in range(2,num):
        if num%i==0:
            flag=1
            break
    if flag==1:
        print("Not prime")
    else:
        print("Prime")
      
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        